version: "3.9"
services:
  # app:
  #   build: .
  #   container_name: application
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - .:/app-node
  #   networks:
  #     - application

  postgres_db:
    image: postgres:14
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
    ports:
      - "5432:5432"
#     networks:
#       - application

# networks:
#   application:
#     driver: bridge
